# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flare_csv.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import os
os.environ['QT_MAC_WANTS_LAYER'] = '1'


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.model = QtGui.QStandardItemModel()
        self.flare_table = QtWidgets.QTableView(self.centralwidget)
        self.flare_table.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.flare_table.setObjectName("flare_table")
        self.flare_table.setModel(self.model)
        self.flare_table.horizontalHeader().setStretchLastSection(True)
        self.flare_table.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.select_flare_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_flare_button.setGeometry(QtCore.QRect(1200, 50, 113, 32))
        self.select_flare_button.setObjectName("select_flare_button")
        self.run_widget_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_widget_button.setGeometry(QtCore.QRect(1200, 510, 161, 32))
        self.run_widget_button.setObjectName("run_widget_button")
        self.flare_info = QtWidgets.QLabel(self.centralwidget)
        self.flare_info.setGeometry(QtCore.QRect(1050, 200, 800, 300))
        self.flare_info.setObjectName("flare_info")
        #self.flare_info.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.flare_val = QtWidgets.QTextEdit(self.centralwidget)
        self.flare_val.setGeometry(QtCore.QRect(1200, 10, 71, 30))
        self.flare_val.setObjectName("flare_val")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.select_flare_button.setText(_translate("MainWindow", "Select Flare"))
        self.run_widget_button.setText(_translate("MainWindow", "Run Widget on Flare"))
        self.flare_info.setText(_translate("MainWindow", ""))
        self.flare_val.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
